language: c
services:
  - mongodb  # this might not launch fast enough - we could need a delay
env:
  global:
    - GAPROOT=gaproot
    - COVDIR=coverage
    - GAP_BOOTSTRAP=minimal
    - GAP_PKGS_TO_CLONE="json io crypting curlInterface profiling"
    - GAP_PKGS_TO_BUILD="json io crypting curlInterface profiling"

branches:
  except:
    - gh-pages

addons:
  apt_packages:
    - libgmp-dev
    - libreadline-dev
    - texlive-latex-extra
    - texlive-fonts-recommended

matrix:
  include:
    - env: GAPBRANCH="stable-4.10"
    - env: CFLAGS="-O2"
      compiler: gcc
    - env: CFLAGS="-O2" CC=clang CXX=clang++
      compiler: clang
    - env: ABI=32
      addons:
        apt_packages:
          - libcurl4-openssl-dev:i386
          - libgmp-dev:i386
          - libreadline-dev:i386
          - texlive-latex-extra:i386
          - texlive-fonts-recommended:i386
          - gcc-multilib
          - g++-multilib

install:
  - pip install --user eve

before_script:
  - export GAPROOT="$HOME/gap"
  - git clone https://github.com/gap-system/pkg-ci-scripts.git scripts
  - scripts/build_gap.sh
script:
  - scripts/build_pkg.sh && scripts/run_tests.sh
after_script:
  - bash scripts/gather-coverage.sh
  - bash <(curl -s https://codecov.io/bash)
