name: Memoisation
version: 0.8
date: 2019-08-20
description: |
    Shared persistent memoisation library for GAP and other systems

authors:
    - name: Michael Torpey
      url: https://mtorpey.github.io/
    - name: Markus Pfeiffer
      url: https://markusp.morphism.de/

maintainers:
    - name: Michael Torpey
      url: https://mtorpey.github.io/

GAP: ">= 4.9"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.6.1"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "curlInterface"
      version: ">= 2.1"
      url: "https://gap-packages.github.io/curlInterface/"
    - name: "io"
      version: ">= 4.0"
      url: "https://gap-packages.github.io/io"
    - name: "json"
      version: ">= 2.0"
      url: "https://gap-packages.github.io/json/"
    - name: "crypting"
      version: ">= 0.8"
      url: "https://gap-packages.github.io/crypting/"

www: https://gap-packages.github.io/Memoisation/
readme: README.md
packageinfo: https://gap-packages.github.io/Memoisation/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/Memoisation/releases/download/v0.8/Memoisation-0.8.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>TP19</span>]   <b class='BibAuthor'>Torpey, M. and Pfeiffer, M.</b>,
     <i class='BibTitle'>Memoisation, Shared persistent memoisation library for GAP and other systems,
             Version 0.8</i>
     (<span class='BibYear'>2019</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/Memoisation/">https://gap-packages.github.io/Memoisation/</a></span>.
    </p>
    

bibtex: |
    @misc{ Memoisation0.8,
      author =           {Torpey, M. and Pfeiffer, M.},
      title =            {{Memoisation},  Shared  persistent memoisation library
                          for GAP and other systems, {V}ersion 0.8},
      month =            {Aug},
      year =             {2019},
      note =             {GAP package},
      howpublished =     {\href    {https://gap-packages.github.io/Memoisation/}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{Memoisation/}}},
      printedkey =       {TP19}
    }

